Fetcher
mattsse/chromiumoxide pull request #115
Opened 2022-12-27 17:18 UTC by Sytten

Fixes #7

This is a first pass, I want to gather some feedback on it. Couple of notes:
- I used the default revision `818858` which matches the PDL `r818844` according to puppeteer (https://github.com/puppeteer/puppeteer/blob/ebd087a31661a1b701650d0be3e123cc5a813bd8/src/revisions.ts).
- I didn't implement the automatic download on launch, but I can if you guys want it.
- I had to do some magic around the feature flags because of https://github.com/rust-lang/cargo/issues/10801, I think my solution is the cleanest that we can get until it is fixed (but we do need to document it).
- I had to implement a custom extract for zip since it currently doesn't support symlinks (https://github.com/zip-rs/zip/pull/213) and those are needed on macos. I think this is cleaner than calling the OS tool (this is what `headless-chrome` does).
- I didn't add tracing into it, but I can if you guys want that.

2022-12-27 17:22 UTC, Sytten commented on chromiumoxide_fetcher/src/browser/runtime.rs
> +pub struct BrowserFetcherRuntime;
We might want an async trait for that if we want to enable both runtimes at the same time?

2022-12-27 17:30 UTC, Sytten commented on Cargo.toml
> +_fetcher-native-tokio = ["fetcher", "chromiumoxide_fetcher/_native-tokio"]
My original plan was to have the features: `async-std-runtime`/`tokio-runtime`, `native-tls`/`rustls-tls` and `fetcher`, but I am not willing to force people to have a dirty lock file for it...

2023-01-02 14:33 UTC, Sytten commented
@mattsse Just want to make sure the PR doesn't become stale

2023-01-02 14:34 UTC, mattsse commented
thanks for the ping, will try to review later today.

2023-01-02 15:54 UTC, mattsse requested changes
tysm!

this looks great.

couple of smol nits. would appreciate brief docs for the public download functions.

2023-01-02 15:54 UTC, mattsse commented on chromiumoxide_fetcher/src/browser/options.rs
> +        }
can derive `Default`

2023-01-02 15:54 UTC, mattsse commented on chromiumoxide_fetcher/src/revision.rs
> +
```suggestion
```

2023-01-02 15:54 UTC, mattsse commented on chromiumoxide_fetcher/src/error.rs
> +
```suggestion
```

2023-01-02 15:54 UTC, mattsse commented on chromiumoxide_fetcher/src/browser/runtime.rs
> +
```suggestion
```

2023-01-02 15:54 UTC, mattsse commented on chromiumoxide_fetcher/src/browser/runtime.rs
> +
```suggestion
```

2023-01-02 15:54 UTC, mattsse commented on chromiumoxide_fetcher/src/browser/revision_info.rs
> +
```suggestion
```

2023-01-02 15:54 UTC, mattsse commented on chromiumoxide_fetcher/src/browser/options.rs
> +
```suggestion
```

2023-01-02 15:54 UTC, mattsse commented on chromiumoxide_fetcher/src/browser/options.rs
> +
```suggestion
```

2023-01-02 15:54 UTC, mattsse commented on chromiumoxide_fetcher/src/browser/fetcher.rs
> +    pub async fn fetch(&self) -> Result<BrowserFetcherRevisionInfo> {
would love some docs here

2023-01-02 18:18 UTC, Sytten commented
@mattsse any reason for removing the spacing between the std, deps and crate imports? I tried to follow the rest of the codebase methodology on that.

2023-01-03 22:33 UTC, mattsse commented
> @mattsse any reason for removing the spacing between the std, deps and crate imports? I tried to follow the rest of the codebase methodology on that.

right, I wasn't very consistent when I wrote this, the main reason is, `rusfmt` won't sort them if the imports are separated by a line

2023-01-03 22:33 UTC, mattsse approved these changes

2023-01-03 22:33 UTC, merged