fallback if snap is targetted
mattsse/chromiumoxide pull request #200
Opened 2024-01-02 11:55 UTC by jloupdef

This PR fixes #186 by reverting the canonalization in case the final binary is snap (when chromium is installed through snap).
We still try to make the path absolute and clean it. It might not be as effective but we only be done when snap is detected and used in a case which wasn't working before.

It will be more elegant to use fs::absolute but the feature is still in nightly rust version.

2024-01-02 14:46 UTC, mattsse requested changes

2024-01-02 14:46 UTC, mattsse commented on src/browser.rs
> +        }
could we move this to a standalone function so we can add a few simple tests?

2024-01-02 21:56 UTC, jloupdef commented on src/browser.rs
> +        }
I updated the code to use subfunctions. Did not make any unit tests, but there isn't many in the project if I am not mistaken. I can confirm it fixes the issue in my case and should not have any impact for others as we only do change when binary is snap.

2024-09-04 18:52 UTC, RonaldRuckus commented
This should have been pushed.

As of now the current ChromiumOxide does not work with chromium installed via snap.

2024-09-04 19:14 UTC, RonaldRuckus commented
For anyone else finding startup issues regarding not recognizing the command. This was the fix. The way the maintainers canonicalize the filepath is wrong. They should have implemented the fix here.

2024-09-06 12:16 UTC, mattsse approved these changes
thanks for checking

2024-09-06 12:17 UTC, merged